### ISSUE TITLE
Does apt-cacher-ng honor proxy settings?

### ISSUE THREAD

**Issue by xuanngo2001** [Efreak/apt-cacher-ng#1]
`apt-cacher-ng` is behind a proxy network. I have set the network proxy settings in /etc/environment and in /etc/apt.conf.d/. Debian is working fine as I can `wget website` and do `apt-get install` through the proxy network .
Now, instead of downloading the same packages again and again, I would like to use apt-cacher-ng. I added `Acquire::http { Proxy "http://127.0.0.1:3142"; };` in `/etc/apt/apt.conf` but it didn't work. I even force it by adding `deb http://127.0.0.1:3142/ftp.debian.org/debian stable main contrib non-free` in sources.list. But it is giving error:

> W: Failed to fetch http://127.0.0.1:3142/ftp.debian.org/debian/dists/stable/main/binary-amd64/Packages  503  DNS error for hostname http.debian.net: Name or service not known. If http.debian.net refers to a configured cache repository, please check the corresponding configuration file.

It looks like `apt-cacher-ng` doesn't support proxy network.

How can I setup `apt-cacher-ng` to go through a proxy network?

**Comment by Efreak** [comment]
No clue, sorry. I mirrored here for easy browsing of the code, because debian alioth is incredibly slow. I'm not actually a developer. I personally only use apt-cacher-ng to mirror software packages for [Linux Deploy](https://github.com/meefik/linuxdeploy).
