### ISSUE TITLE
Repo not up-to-date?

### ISSUE THREAD

**Issue by makefu** [Efreak/apt-cacher-ng#2]
Hey ho,

it seems like the repo is not up-to-date anymore. The latest upstream release is 0.8.4 , maybe set up an automatic mirror of upstream?

cheers

**Comment by Efreak** [comment]
I don't have any way of setting up an automatic mirror and no longer have interest in this. I cloned this because I couldn't find an easy-to-browse archive of the source code that I could view in the browser with code highlighting (ie, without downloading the entire thing to my computer and viewing it in an IDE).

**Comment by Efreak** [comment]
I just tried adding [the original repo](https://alioth.debian.org/anonscm/git/apt-cacher-ng/apt-cacher-ng.git) with the following commands, and according to them, [master _is_ up to date](http://i.imgur.com/HWj6bfJ.png). I'm not sure what else to do...

``` bash
git clone git@github.com:Efreak/apt-cacher-ng.git
cd apt-cacher-ng/
git remote add upstream https://alioth.debian.org/anonscm/git/apt-cacher-ng/apt-cacher-ng.git
git fetch --all
git checkout master
git merge upstream/master
```

**Comment by Efreak** [comment]
Never mind. I just re-mirrored the entire thing, including other branches/tags/etc. (this repo is now an exact clone of the official repo on alioth at this time)

If you need this in the future (I no longer need it, so am unlikely to keep it up to date), please follow the steps yourself (this will push it into your own repo, not mine; modify the last line if you like)

``` bash
git clone --bare https://alioth.debian.org/anonscm/git/apt-cacher-ng/apt-cacher-ng.git
cd apt-cacher-ng.git
git push --mirror git@github.com:makefu/apt-cacher-ng
```

**Comment by makefu** [comment]
hi @Efreak thanks making yourself go through the process again and even documenting it. i really appreciate it :+1:
